### ISSUE TITLE
Syntax error IE11

### ISSUE THREAD

**Issue by ElisabethStereosuper** [philippkuehn/vue-mailchimp-subscribe#1]
There is a syntax error thrown by a package you're using called split-on-first.
https://github.com/sindresorhus/split-on-first/issues/6

Maybe you could use something else?

**Comment by philippkuehn** [comment]
I don't want to support IE11 either. Sorry!

**Comment by max8hine** [comment]
@ElisabethStereosuper,

I am having the same the IE11 issue from **query-string**

> This module targets Node.js 6 or later and the latest version of Chrome, Firefox, and Safari. If you want support for older browsers, or, if your project is using create-react-app v1, use version 5: npm install query-string@5.

So, I copied the lib to a customised js file and installed `npm install jsonp query-string@5` to solve the issue.
