### ISSUE TITLE
Is this working? Perpetual Loading 

### ISSUE THREAD

**Issue by kieron** [philippkuehn/vue-mailchimp-subscribe#4]
Hey! 

Thanks for this package, I am currently seeing loading forever, and then a timeout, BUT, it does subscribe me successfully, is anyone else seeing this?

I am getting a Cross-Origin Read Blocking (CORB) issue in my console, i wonder if that is blocking.

Thanks

**Comment by kieron** [comment]
NVM, I am an idiot.

**Comment by RonnyCalderon** [comment]
@kieron how did you fix it? I'm an idiot too.

**Comment by kieron** [comment]
@RonnyCalderon Sorry I realise its incredibly unhelpful to just say I fixed it- let me see if I can find my commits relating too it, might shed some light.

**Comment by kieron** [comment]
@RonnyCalderon Here's what I think is all of the code, so maybe just check it against your own, I have a feeling I was missing some of the ID's on the `mailchimp-subscribe` element?

```
<mailchimp-subscribe
        url="https://something.us10.list-manage.com/subscribe/post-json" 
        user-id="215c2c123123123123f912"
        list-id="a1231233"
        @error="onError"
        @success="onSuccess"
      >
          <template v-slot="{ subscribe, setEmail, error, success, loading }">
            <div><form @submit.prevent="subscribe">
              <div class="flex flex-col rounded-lg overflow-hidden sm:flex-row">
                <input
                  placeholder="Enter your email"
                  class="py-3 px-4 bg-gray-200 text-gray-800 border-gray-300 border-2 outline-none placeholder-gray-700 focus:bg-gray-100"
                  type="email"
                  @input="setEmail($event.target.value)"
                />
                <button
                  class="py-3 px-4 bg-gray-700 tracking-widest text-gray-100 font-semibold uppercase md:rounded-r-md hover:bg-gray-600"
                  id="mailSubmit"
                  type="submit"
                  >
                  
                  Submit
                </button>
                
              </div>

            </form>
            <div class="flex py-5 pl-2 header-font tracking-widest text-md">
                  <div v-if="error">{{ error }}</div>
                  <div v-if="success">You will receive a confirmation email!</div>
                  <div v-if="loading">Processing...</div>
                </div>
                </div>
          </template>
        </mailchimp-subscribe>

<script>
import MailchimpSubscribe from "vue-mailchimp-subscribe";

export default {
  components: {
    MailchimpSubscribe,
  },
  methods: {
    onError() {
      // handle error
    },
    onSuccess() {
     //
    },
  },
};
</script>
```

**Comment by RonnyCalderon** [comment]
Thank you @kieron your comment was beyond helpful. Turns out I was posting to the wrong URL.

The docs mention posting to http://mailchimp.us8.list-manage.com/subscribe/post

https://mailchimp.com/es/help/host-your-own-signup-forms/
![image](https://user-images.githubusercontent.com/16216967/104975524-8252f600-59c0-11eb-979f-fbf889cbdc4d.png)

Notice that you're posting to url="...../post-json" 

I changed the post request to look like yours and it worked. Thanks a lot

**Comment by kieron** [comment]
Awesome glad I could help! Your welcome @RonnyCalderon 😁
