### ISSUE TITLE
Mailchimp doc

### ISSUE THREAD

**Issue by asefcamel** [philippkuehn/vue-mailchimp-subscribe#7]
any documentation about how to get the url, list id & user-id ?

**Comment by asefcamel** [comment]
Okey just found the doc in an other plugin.

About
This is just a really simple component that let's you use MailChimp's awesome email signup form but with a little bit more of a modern style. Normally for a component this simple I wouldn't really think to share it, but it ends up being really nice to use in things like Gridsome sites where you really don't want to bring a backend anywhere near your site. It's super easy to use - just follow the steps below to generate the url prop you need to pass to the component.

Go to your MailChimp admin. Click on Create, the Signup Form. Now, choose your audience, and stay on the Embedded form option and click Begin.

On the next screen, you'll see some demos for some embedded forms MailChip is offering. We don't want those - but we do want to url they bring. Go into the form and grab the url from the <form></form> action attribute. For me, this looks something like the following:

https://XXXXX.us4.list-manage.com/subscribe/post?u=XXXXXXXXXXXXXXXXXXXXXXXX&id

**Comment by rohitnishad613** [comment]
how you get the userID?

**Comment by rohitnishad613** [comment]
Actually, I found it, let me make it simple for searchers,
Navigate to:

Audience > Signup forms > Embedded forms 
Here, In the code section look for action attribute of form,

Your list ID and user ID is there as `u` and `id`  query parameter.
